import { Project } from "./types";

export const projects: Project[] = [
     {
          title: "AI Attorney",
          description: "Collaborated on backend development for a legal tech mobile app using Node.js, TypeScript, and Prisma.",
          tags: ["Node.js", "TypeScript", "Prisma"],
          github: "",
          live: "https://www.aiattorney.com.pk/",
     },
     {
          title: "Xora",
          description: "AI-powered platform designed to automate business workflows and streamline operations. (This is just a dummy landing page)",
          tags: ["React", "Tailwind CSS"],
          github: "https://github.com/Waleed-Ahmad-dev/Xora",
          live: "https://xora-six-xi.vercel.app/",
     },
     {
          title: "Yoom",
          description: "Real-time video conferencing solution with sleek UI and dynamic room creation.",
          tags: ["Next.js", "Stream Video SDK", "Tailwind CSS"],
          github: "https://github.com/Waleed-Ahmad-dev/Yoom",
          live: "https://yoom-eight-eta.vercel.app/",
     },
     {
          title: "Shadow Cart - Ecommerce Store",
          description: "Responsive and functional ecommerce platform with cart, product view, and checkout.",
          tags: ["React", "Tailwind CSS"],
          github: "https://github.com/Waleed-Ahmad-dev/Shadow_Cart",
          live: "https://shadow-store-ten.vercel.app/",
     },
     {
          title: "Memory Game",
          description: "Interactive memory card game to test and train your short-term memory.",
          tags: ["React", "CSS"],
          github: "https://github.com/Waleed-Ahmad-dev/MemoryGame_React",
          live: "https://memory-game-react-fawn.vercel.app/",
     },
     {
          title: "TaskFlow - Todo List",
          description: "Minimalist task management application with drag-and-drop organization.",
          tags: ["React", "JavaScript"],
          github: "https://github.com/Waleed-Ahmad-dev/to-do-list-react",
          live: "https://to-do-list-react-sandy.vercel.app/",
     },
     {
          title: "Digital Library",
          description: "Frontend app for a digital library showcasing book collections and browsing experience.",
          tags: ["HTML", "CSS", "JavaScript"],
          github: "https://github.com/Waleed-Ahmad-dev/Library",
          live: "https://waleed-ahmad-dev.github.io/Library/",
     },
     {
          title: "Drawing App",
          description: "Simple and intuitive drawing canvas app built with vanilla JavaScript.",
          tags: ["HTML", "CSS", "JavaScript"],
          github: "https://github.com/Waleed-Ahmad-dev/drawing-app",
          live: "https://waleed-ahmad-dev.github.io/drawing-app/",
     },
     {
          title: "Whack a Mole Game",
          description: "A fun browser game that challenges your reaction time.",
          tags: ["HTML", "CSS", "JavaScript"],
          github: "https://github.com/Waleed-Ahmad-dev/Whack-a-Mole",
          live: "https://waleed-ahmad-dev.github.io/Whack-a-Mole/",
     },
     {
          title: "Tic Tac Toe",
          description: "Classic Tic Tac Toe game with clean UI and smart opponent logic.",
          tags: ["HTML", "CSS", "JavaScript"],
          github: "https://github.com/Waleed-Ahmad-dev/Tic-Tac-Toe",
          live: "https://waleed-ahmad-dev.github.io/Tic-Tac-Toe/",
     },
     {
          title: "Weather App",
          description: "Weather dashboard with real-time data and location-based updates.",
          tags: ["JavaScript", "API Integration"],
          github: "https://github.com/Waleed-Ahmad-dev/Weather-App",
          live: "https://waleed-ahmad-dev.github.io/Weather-App/",
     },
     {
          title: "Calculator",
          description: "Responsive calculator with keyboard support and clean interface.",
          tags: ["HTML", "CSS", "JavaScript"],
          github: "https://github.com/Waleed-Ahmad-dev/Calculator",
          live: "https://waleed-ahmad-dev.github.io/Calculator/",
     },
     {
          title: "Rock Paper Scissors Game",
          description: "Simple game built with JavaScript and DOM manipulation techniques.",
          tags: ["HTML", "CSS", "JavaScript"],
          github: "https://github.com/Waleed-Ahmad-dev/Rock-Papper-Scissors-Game",
          live: "https://waleed-ahmad-dev.github.io/Rock-Papper-Scissors-Game/",
     },
];